name: Deploy application to stage

on:
  push:
    branches:
      - 'stage'  # stage branch

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Concurrency takes any arbitrary value, but this prevents multiple deployments happening at the same time.
    # We set the concurrency to stage for this deployment workflow.
    concurrency: stage
    environment:
      name: stage
      url: https://ma.stage.qlicks.nl
    container: maretti2.hypernode.io/hypernode/deploy:3-php8.1-node18
    steps:
    - uses: actions/checkout@v3
    - name: download build artifact
      uses: actions/download-artifact@v3
      with:
        name: deployment-build
        path: build/
    - uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-composer
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: mkdir -p $HOME/.ssh
    - run: hypernode-deploy deploy stage -vvv  # Deploy stage defined in deploy.php
